apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-api-ingress
  annotations:
    # This tells your controller to pick this up
    kubernetes.io/ingress.class: alb
    # Makes the Load Balancer accessible from the public internet
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Modern EKS standard: Sends traffic directly to Pod IPs
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: data-api-service # This must match the name in service.yaml
                port:
                  number: 80