apiVersion: v1
kind: Service
metadata:
  name: data-api-service
spec:
  # This finds your pods based on the label you gave them in your deployment
  selector:
    app: data-api 
  ports:
    - protocol: TCP
      port: 80         # The port the Service listens on
      targetPort: 8080 # The port your Go/Gin app is listening on (0.0.0.0:8080)
  # NodePort is required for the AWS Application Load Balancer to talk to the cluster
  type: NodePort